tcp:
  server:
    port: 65535
    max-connection: 100
    key-store: ${user.dir}/src/main/resources/keystore-for-server.jks
    key-store-password: secret
    trust-store: ${user.dir}/src/main/resources/truststore-for-server.jks
    trust-store-password: secret
  client:
    host: localhost
    port: ${tcp.server.port}
    connection-timeout: 1000 # millis
    read-timeout: 5000 # millis
    key-store: ${user.dir}/src/main/resources/keystore-for-client.jks
    key-store-password: secret
    trust-store: ${user.dir}/src/main/resources/truststore-for-client.jks
    trust-store-password: secret
    pool:
      min-idle: 10
      max-idle: 10
      max-total: ${tcp.server.max-connection}