tcp:
  server:
    port: 65535
    max-connection: 100
  client:
    host: localhost
    port: ${tcp.server.port}
    connection-timeout: 1000 # millis
    read-timeout: 5000 # millis
    pool:
      min-idle: 10
      max-idle: 10
      max-total: ${tcp.server.max-connection}
